function de_tu_freiberg_informatik_vonwenckstern_Agricola(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',hc='.cache.html',_='/',lb='//',Wb='2FB2116A165D7F97E48141DBF52DE4D7',Xb='5878F0FC39D56FA8735A27DE565322D3',Yb='6BD4A6832654720D657D2EDD2592BC7D',Zb='6CC394129121370F8017D28A377263A0',$b='7344878DE59D1B0E74E9827C81B31C5F',_b='7A3C03F30DDD351C73A2B802DBEEE911',ac='82B5DE4450A416D19E3C72D782A6D3D6',bc='877CA350CF2F37C4793B78CDC78C2E9B',cc='9F97132081CF0C3825D8D803981C1BC5',gc=':',pb='::',pc='<script defer="defer">de_tu_freiberg_informatik_vonwenckstern_Agricola.onInjectionDone(\'de.tu_freiberg.informatik.vonwenckstern.Agricola\')<\/script>',hb='<script id="',sb='=',$='?',Eb='Android',ub='Bad handler "',dc='CFDCA829AB53E355639024DEF595EF29',ec='D26DC3F2FBC6FD5976FDB9E93A5BE360',oc='DOMContentLoaded',fc='E5A6958E0B7006D791FE9EA138020956',jb='SCRIPT',gb='__gwt_marker_de.tu_freiberg.informatik.vonwenckstern.Agricola',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',rb='content',Q='de.tu_freiberg.informatik.vonwenckstern.Agricola',eb='de.tu_freiberg.informatik.vonwenckstern.Agricola.nocache.js',ob='de.tu_freiberg.informatik.vonwenckstern.Agricola::',Y='end',Qb='gecko',Rb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',ic='gwt/standard/standard.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',nc='head',Ub='hosted.html?de_tu_freiberg_informatik_vonwenckstern_Agricola',mc='href',Fb='iPad',Db='iPhone',Pb='ie6',Ob='ie8',Nb='ie9',yb='iframe',ab='img',Cb='ismobile',zb="javascript:''",jc='link',Tb='loadExternalRefs',mb='meta',Bb='moduleRequested',X='moduleStartup',Mb='msie',nb='name',Hb='no',Jb='opera',Ab='position:absolute;width:0;height:0;border:none',kc='rel',Lb='safari',db='script',Vb='selectingPermutation',R='startup',lc='stylesheet',fb='undefined',Sb='unknown',Ib='user.agent',Kb='webkit',Gb='yes';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}de_tu_freiberg_informatik_vonwenckstern_Agricola=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){return navigator.userAgent.indexOf(Db)>-1||(navigator.userAgent.indexOf(Eb)>-1||navigator.userAgent.indexOf(Fb)>-1)?Gb:Hb};v[Cb]={no:0,yes:1};w[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Jb)!=-1}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1&&n.documentMode>=9}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&n.documentMode>=8}())return Ob;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;return Sb};v[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};de_tu_freiberg_informatik_vonwenckstern_Agricola.onScriptLoad=function(){if(I){r=true;C()}};de_tu_freiberg_informatik_vonwenckstern_Agricola.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Ub;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Vb});if(!B()){try{G([Hb,Nb],Wb);G([Gb,Nb],Xb);G([Hb,Ob],Yb);G([Gb,Rb],Zb);G([Hb,Rb],$b);G([Hb,Pb],_b);G([Gb,Pb],ac);G([Gb,Ob],bc);G([Gb,Lb],cc);G([Hb,Jb],dc);G([Gb,Jb],ec);G([Hb,Lb],fc);K=x[H(Cb)][H(Ib)];var M=K.indexOf(gc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+hc}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[ic]){var a=n.createElement(jc);__gwt_stylesLoaded[ic]=a;a.setAttribute(kc,lc);a.setAttribute(mc,t+ic);n.getElementsByTagName(nc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(oc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(oc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:T});n.write(pc)}
de_tu_freiberg_informatik_vonwenckstern_Agricola();