package de.tu_freiberg.informatik.vonwenckstern.client.model;

public enum BackgroundCard {
	NONE, SHEEP, ACQUISITION, FENCE, SEEDING_BACKING, FAMILIY_ADDITION2, STONE2, 
	RESTAURATION, BOAR, VEGETABLE, STONE4, COW, PLOWING_SOWING, FAMILY_ADDITION5, 
	RESTAURATION_FENCE, ONE_WOOD,  TWO_CLAY, TWO_WOOD, REED_STONE_FOOD, CABARET,
}
